// Pre-rendered chrome glyphs from liquid-chrome-font (CC BY 4.0).
// Metrics mirror demo/composer.html — h scales height, dy shifts descenders.
export type GlyphMetric = { h: number; dy: number; aspect: number };

export const GLYPH_METRICS: Record<string, GlyphMetric> = {
  a: { h: 1.0, dy: 0.02, aspect: 0.975 },
  b: { h: 1.45, dy: 0.02, aspect: 0.594 },
  c: { h: 1.05, dy: 0.02, aspect: 0.781 },
  d: { h: 1.3, dy: 0.02, aspect: 0.7 },
  e: { h: 1.05, dy: 0.02, aspect: 0.881 },
  f: { h: 1.55, dy: 0.02, aspect: 0.569 },
  g: { h: 1.35, dy: 0.05, aspect: 0.694 },
  h: { h: 1.4, dy: 0.02, aspect: 0.688 },
  i: { h: 1.3, dy: 0.02, aspect: 0.4 },
  j: { h: 1.45, dy: 0.03, aspect: 0.45 },
  k: { h: 1.35, dy: 0.02, aspect: 0.762 },
  l: { h: 1.25, dy: 0.02, aspect: 0.469 },
  m: { h: 1.0, dy: 0.02, aspect: 1.221 },
  n: { h: 1.0, dy: 0.02, aspect: 0.994 },
  o: { h: 1.05, dy: 0.02, aspect: 0.956 },
  p: { h: 1.3, dy: 0.14, aspect: 0.762 },
  q: { h: 1.3, dy: 0.06, aspect: 0.719 },
  r: { h: 1.05, dy: 0.02, aspect: 0.8 },
  s: { h: 1.1, dy: 0.02, aspect: 0.7 },
  t: { h: 1.4, dy: 0.02, aspect: 0.575 },
  u: { h: 1.0, dy: 0.02, aspect: 1.0 },
  v: { h: 1.05, dy: 0.02, aspect: 0.9 },
  w: { h: 1.05, dy: 0.02, aspect: 1.311 },
  x: { h: 1.1, dy: 0.02, aspect: 0.869 },
  y: { h: 1.3, dy: 0.04, aspect: 0.812 },
  z: { h: 0.95, dy: 0.02, aspect: 0.881 },
  '0': { h: 1.35, dy: 0.02, aspect: 0.731 },
  '1': { h: 1.4, dy: 0.02, aspect: 0.469 },
  '2': { h: 1.35, dy: 0.02, aspect: 0.725 },
  '3': { h: 1.4, dy: 0.02, aspect: 0.631 },
  '4': { h: 1.45, dy: 0.02, aspect: 0.731 },
  '5': { h: 1.35, dy: 0.02, aspect: 0.806 },
  '6': { h: 1.4, dy: 0.02, aspect: 0.681 },
  '7': { h: 1.5, dy: 0.02, aspect: 0.781 },
  '8': { h: 1.4, dy: 0.02, aspect: 0.662 },
  '9': { h: 1.45, dy: 0.02, aspect: 0.631 },
};

export const GLYPH_SOURCES: Record<string, number> = {
  a: require('../assets/liquid-chrome-glyphs/a.png'),
  b: require('../assets/liquid-chrome-glyphs/b.png'),
  c: require('../assets/liquid-chrome-glyphs/c.png'),
  d: require('../assets/liquid-chrome-glyphs/d.png'),
  e: require('../assets/liquid-chrome-glyphs/e.png'),
  f: require('../assets/liquid-chrome-glyphs/f.png'),
  g: require('../assets/liquid-chrome-glyphs/g.png'),
  h: require('../assets/liquid-chrome-glyphs/h.png'),
  i: require('../assets/liquid-chrome-glyphs/i.png'),
  j: require('../assets/liquid-chrome-glyphs/j.png'),
  k: require('../assets/liquid-chrome-glyphs/k.png'),
  l: require('../assets/liquid-chrome-glyphs/l.png'),
  m: require('../assets/liquid-chrome-glyphs/m.png'),
  n: require('../assets/liquid-chrome-glyphs/n.png'),
  o: require('../assets/liquid-chrome-glyphs/o.png'),
  p: require('../assets/liquid-chrome-glyphs/p.png'),
  q: require('../assets/liquid-chrome-glyphs/q.png'),
  r: require('../assets/liquid-chrome-glyphs/r.png'),
  s: require('../assets/liquid-chrome-glyphs/s.png'),
  t: require('../assets/liquid-chrome-glyphs/t.png'),
  u: require('../assets/liquid-chrome-glyphs/u.png'),
  v: require('../assets/liquid-chrome-glyphs/v.png'),
  w: require('../assets/liquid-chrome-glyphs/w.png'),
  x: require('../assets/liquid-chrome-glyphs/x.png'),
  y: require('../assets/liquid-chrome-glyphs/y.png'),
  z: require('../assets/liquid-chrome-glyphs/z.png'),
  '0': require('../assets/liquid-chrome-glyphs/0.png'),
  '1': require('../assets/liquid-chrome-glyphs/1.png'),
  '2': require('../assets/liquid-chrome-glyphs/2.png'),
  '3': require('../assets/liquid-chrome-glyphs/3.png'),
  '4': require('../assets/liquid-chrome-glyphs/4.png'),
  '5': require('../assets/liquid-chrome-glyphs/5.png'),
  '6': require('../assets/liquid-chrome-glyphs/6.png'),
  '7': require('../assets/liquid-chrome-glyphs/7.png'),
  '8': require('../assets/liquid-chrome-glyphs/8.png'),
  '9': require('../assets/liquid-chrome-glyphs/9.png'),
};
