// Curated set of well-known cities. Used as a fail-safe allowlist when a
// user-entered city is validated against the live geocoder (Open-Meteo), so a
// brief geocoder outage — or a naming-convention gap the geocoder spells
// differently (e.g. it calls "Washington DC" simply "Washington") — never
// wipes a genuinely real city from Explore. Lives in shared/ so both the
// Expo client and the server can import it.
export const COMMON_CITIES = [
  'Amsterdam',
  'Athens',
  'Atlanta',
  'Austin',
  'Bangkok',
  'Barcelona',
  'Beijing',
  'Berlin',
  'Bogotá',
  'Boston',
  'Brussels',
  'Budapest',
  'Buenos Aires',
  'Cairo',
  'Cape Town',
  'Chicago',
  'Cologne',
  'Copenhagen',
  'Dallas',
  'Delhi',
  'Denver',
  'Detroit',
  'Dubai',
  'Dublin',
  'Frankfurt',
  'Geneva',
  'Hamburg',
  'Helsinki',
  'Hong Kong',
  'Houston',
  'Istanbul',
  'Jakarta',
  'Johannesburg',
  'Kyoto',
  'Lagos',
  'Las Vegas',
  'Lisbon',
  'London',
  'Los Angeles',
  'Madrid',
  'Manila',
  'Melbourne',
  'Mexico City',
  'Miami',
  'Milan',
  'Minneapolis',
  'Montreal',
  'Moscow',
  'Mumbai',
  'Munich',
  'Nairobi',
  'Nashville',
  'New Orleans',
  'New York',
  'Osaka',
  'Oslo',
  'Paris',
  'Philadelphia',
  'Phoenix',
  'Portland',
  'Prague',
  'Rio de Janeiro',
  'Rome',
  'San Diego',
  'San Francisco',
  'Santiago',
  'São Paulo',
  'Seattle',
  'Seoul',
  'Shanghai',
  'Singapore',
  'Stockholm',
  'Sydney',
  'Taipei',
  'Tel Aviv',
  'Tokyo',
  'Toronto',
  'Vancouver',
  'Vienna',
  'Warsaw',
  'Washington DC',
  'Zurich',
] as const;

// Lowercased city name -> canonical display casing, for fast allowlist lookups.
export const COMMON_CITY_BY_KEY = new Map<string, string>(
  COMMON_CITIES.map((c) => [c.toLowerCase(), c] as [string, string])
);
